### ISSUE TITLE
License Activation Issues

### ISSUE THREAD

**Issue by matthew-schiller** [squarebit-studios/touchpose-public#1]
1. Initial install and activation worked fine. TouchPose highlights and selects.
2. Machine was restarted
3. New Maya opened
4. Scene with TouchPose rig opened. Turning on TouchPose through touchpose menu check box errors (Error A) but things are still selectable but no highlighting is happening.
5. User is un-able to re-activate license because it is trying to unload touch plugins in the scene. (Error B)
6. Trying to re-activate errors even in a clean Maya scene. (Error C)
7. I verified licenses were available from License Spring
8. Restart Maya
9. Re-activating works without error
10. TouchPose is selecting but not highlighting. Highlighting has not worked again since the restart of the machine. Made sure user was in texture preview mode.
11. User deletes touchpose module files and does a fresh drag and drop install
12. Install gets to a point and hangs (error D). To License key widget never pops up.
13. Re-opening Maya nd the install is working

Error A
```python
('enabled', (True,))
# Error: module 'maya.cmds' has no attribute 'touchPose'
# # Traceback (most recent call last):
# #   File "Documents\dev\squarebit\touchpose\build\building_touchpose\pre_scripts\touchpose\touch_commands_model.py", line 621, in touchpose.touch_commands_model.toggle_enabled
# # AttributeError: module 'maya.cmds' has no attribute 'touchPose'
```

Error B
```python
# Warning: No valid touchpose license
# Warning: Plug-in, "touch_shape.py", is already loaded.  Skipped.
# Warning: Plug-in, "touch_texture.mll", is already loaded.  Skipped.
from maya import cmds;cmds.unloadPlugin("touch_commands")
# Result: ['touch_commands']
from maya import cmds;cmds.unloadPlugin("touch_texture")
# Error: Plug-in, "touch_texture", cannot be unloaded because it is still in use
# # Traceback (most recent call last):
# #   File "<maya console>", line 1, in <module>
# # RuntimeError: Plug-in, "touch_texture", cannot be unloaded because it is still in use
from maya import cmds;cmds.unloadPlugin("touch_shape")
# Error: Plug-in, "touch_shape", cannot be unloaded because it is still in use
# # Traceback (most recent call last):
# #   File "<maya console>", line 1, in <module>
# # RuntimeError: Plug-in, "touch_shape", cannot be unloaded because it is still in use
import touchpose.ui.license_key_widget as lkw; lkw.LicenseKeyWidget.set_active_state()
```

Error C
```python
# Warning: No valid touchpose license
selectType -byName touchShapeSelection 0;
from maya import cmds;cmds.unloadPlugin("touch_commands")
# Result: ['touch_commands']
from maya import cmds;cmds.unloadPlugin("touch_texture")
# Result: ['touch_texture']
from maya import cmds;cmds.unloadPlugin("touch_shape")
# Result: ['touch_shape']
updateComponentSelectionMasks;
updateObjectSelectionMasks;
dR_selTypeChanged("");
import touchpose.ui.license_key_widget as lkw; lkw.LicenseKeyWidget.set_active_state()
```

error D

```
2023-03-17 10:20:39 : C:\Users\johnt\Documents\maya\modules\touchpose
2023-03-17 10:20:39 : Uninstalled Successfully!
2023-03-17 10:20:40 : Copying: C:\Users\johnt\Downloads\drive-download-20230316T201003Z-001\touchpose_windows_v2_0_1\touchpose_windows to C:\Users\johnt\Documents\maya\modules\touchpose
2023-03-17 10:20:40 : Moved: C:\Users\johnt\Documents\maya\modules\touchpose\touchpose.mod
...to C:\Users\johnt\Documents\maya\modules
2023-03-17 10:20:40 : Added to PYTHONPATH: C:\Users\johnt\Documents\maya\modules\touchpose\scripts39
```

**Comment by matthew-schiller** [comment]
Core issue was plugin was not loading on restart of Maya because stored license key was not getting loaded. This has been patched in v2.0.2
